### ISSUE TITLE
Curious if the lint config is broken, or if documentation is wrong

### ISSUE THREAD

**Issue by jondkelley** [PeterDaveHello/docker-markdownlint#2]
At https://www.npmjs.com/package/markdownlint-cli if you look at Configuration heading, it says

> markdownlint-cli reuses the rules from markdownlint package.
> Configuration is stored in JSON, JSONC, YAML, or INI files in the same config format.
> 
> A sample configuration file:
> 
> {
>   "default": true,
>   "MD003": { "style": "atx_closed" },
>   "MD007": { "indent": 4 },
>   "no-hard-tabs": false,
>   "whitespace": false
> }

So I tried it out...

```

$ cat .markdownlint.json
{
  "default": true,
  "line-length": false,
  "no-bare-urls": false,
  "ul-start-left": false,
  "blanks-around-lists": false,
  "no-hard-tabs": true,
  "no-trailing-spaces": { "br_spaces": 0 }
}
```
```

$ docker run -v $PWD:/md peterdavehello/markdownlint markdownlint --rules .markdownlint.json  resume.md.jinja2
/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:799
      throw error;
      ^

Error: Property 'names' of custom rule at index 0 is incorrect.
    at newError (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:33:14)
    at forProperty (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:42:18)
    at Array.forEach (<anonymous>)
    at forRule (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:37:25)
    at Array.forEach (<anonymous>)
    at validateRuleList (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:29:12)
    at lintInput (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:703:19)
    at Function.markdownlintSync [as sync] (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:797:3)
    at lintAndPrint (/usr/local/lib/node_modules/markdownlint-cli/markdownlint.js:295:35)
    at Object.<anonymous> (/usr/local/lib/node_modules/markdownlint-cli/markdownlint.js:300:3)
```

**Comment by PeterDaveHello** [comment]
Hi @jondkelley,

The only reason you got the error because that `--rules` is being wrongly used here. By default, you don't need to specify the config file when you're using default config filename, and if you really want to use it, the proper parameter for it is `--config`, not `--rules`, I believe that you might misunderstand what a rule of markdownlint is, hope this doc will help: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
